name: tofu
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - cffi=1.16.0
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - importlib-metadata=6.0.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.9
  - ld_impl_linux-64=2.36.1
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgomp=12.1.0
  - libnsl=2.0.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=2.32.1
  - libzlib=1.2.12
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - openssl=3.0.12
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.1.2
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.9
  - pyzmq=23.2.0
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - readline=8.1.2
  - referencing=0.30.2
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=63.2.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.39.1
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=4.0.5
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.12
  - pip:
      - certifi==2022.6.15
      - charset-normalizer==2.1.0
      - cmake==3.28.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.47.0
      - fsspec==2023.12.2
      - idna==3.3
      - importlib-resources==6.1.1
      - joblib==1.1.0
      - kiwisolver==1.4.5
      - lit==17.0.6
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.23.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - pillow==9.2.0
      - pyparsing==3.1.1
      - requests==2.28.1
      - scikit-learn==1.1.1
      - scipy==1.8.1
      - sympy==1.12
      - termcolor==1.1.0
      - threadpoolctl==3.1.0
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchdata==0.7.1
      - torchtext==0.16.2
      - torchvision==0.16.2
      - tqdm==4.64.0
      - triton==2.1.0
      - typing-extensions==4.3.0
      - urllib3==1.26.10
